version: "3"
services:
  postgres:
    container_name: postgres-dev
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  redis:
    container_name: 'redis-db'
    image: 'redis:alpine'
    command: redis-server --requirepass qwerty12345
    ports:
      - '6379:6379'
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: qwerty12345
    ports:
      - 5672:5672
      - 15672:15672
